# Input Values
client_id = "client_id"
client_secret = "client_secret"
munchkin_id = "munchkin_id"
staticListId = "1234"
staticListName = "db"
start = "2022-03-31T00:00:00-0500"
end = "2022-06-01T00:59:00-0500"

# DO NOT EDIT PAST THIS LINE
from marketorestpython.client import MarketoClient
import time
import dateutil.parser
import pandas as pd

#https://github.com/jepcastelein/marketo-rest-python

# Marketo API Information
api_limit = None
max_retry_time = None
requests_timeout = (3.0, 10.0)
mc = MarketoClient(munchkin_id, client_id, client_secret, api_limit, max_retry_time, requests_timeout=requests_timeout)

output_file = 'data.csv'
export_id_array = []
block_start_date = ""
block_end_date = ""

# Date Block Generator
start_date = dateutil.parser.isoparse(start)
end_date = dateutil.parser.isoparse(end)
dates = pd.date_range(start_date, end_date, freq="M").to_pydatetime().tolist()

date_list = []
block_list = []

for i in range(len(dates)):
    date_list.append(dates[i].isoformat())

for x in range(len(date_list)-1):
    block_list.append([date_list[x], date_list[x+1]])

output_fields = [
    "X5th_day_checkbox__c",
    "X7th_day_checkbox__c",
    "ABM_Category__c",
    "ABM_Category__c_contact",
    "ABM_Category__c_lead",
    "aBMInfluencerScore",
    "aBMMQLsScore",
    "Academic_Opt_Out__c",
    "Americas_Account_Category__c",
    "Account_CC__c",
    "Account_Contact_Role__c",
    "Account_Creation_Request__c",
    "CurrencyIsoCode_account",
    "Account_Entitlement_Status__c",
    "Account_Entitlement_Status__c_contact",
    "Account_ID_18_Digit__c",
    "NameLocal",
    "Account_Revenue_Tier__c",
    "AccountSource",
    "Account_Type__c",
    "Acquisition_Channel__c",
    "mktoAcquisitionDate",
    "Act_Now__c",
    "Act_Now_Date__c",
    "Act_Now_Reset_Date__c",
    "Active_MSC_One_Customer__c",
    "Active_MSC_One_Tokens__c",
    "ACV__c",
    "addtoNurture",
    "address",
    "Address_lead",
    "AgencyNo1__c",
    "AgencyNo2__c",
    "Agreement_Date__c",
    "Agreement_version__c",
    "Americas_Territory__c",
    "annualRevenue",
    "Annual_Sales__c",
    "anonymousIP",
    "Apex_IRT_Contact__c",
    "Approved__c",
    "Areas_of_Concerns__c",
    "Assigned_Overlay__c",
    "assignedOverlayB",
    "Assigned_Overlay_Email__c",
    "atEventComments",
    "atEventFollowUp",
    "Products__c",
    "behaviorScore",
    "billingStreet",
    "BillingAddress",
    "billingCity",
    "billingCountry",
    "BillingCountryCode",
    "BillingGeocodeAccuracy",
    "BillingLatitude",
    "BillingLongitude",
    "billingPostalCode",
    "billingState",
    "BillingStateCode",
    "blackListed",
    "blackListedCause",
    "Bounce__c",
    "bounceDate",
    "Business_Unit__c",
    "Bypass_Duplicate_Rules__c",
    "CAD_Software__c",
    "CAD_Usage__c",
    "campaignCode",
    "canReceiveEmail",
    "Cancel_Time_Based_Workflow__c",
    "capability",
    "Case_Contact_Country__c",
    "Case_Status__c",
    "CFD_Application__c",
    "CFD_Newsletter__c",
    "CFD_Usage__c",
    "Channel_Manager_Reject__c",
    "ChannelProgramLevelName",
    "ChannelProgramName",
    "city",
    "Closed_Lost_Date_MKTO__c",
    "Comment_History__c",
    "Company__c",
    "company",
    "Company_Name_Local_Language__c",
    "Company_name_Phonetic__c",
    "mktoCompanyNotes",
    "consentBlogUpdates",
    "Consent_Communications_Preferences__c",
    "consentMagazine",
    "consentMagazineDelivery",
    "consentMobileSMS",
    "consentNeuesAusCAEWelt",
    "consentNewsUpdates",
    "consentOptOutSurvey",
    "Consent_Personal_Data_Review_Request__c",
    "consentProductofInterest",
    "productofInterestCradle",
    "productofInterestExstream",
    "productofInterestFFT",
    "productofInterestFTI",
    "productofInterestMSC",
    "consentProductofInterestMSCApex",
    "consentProductofInterestRomax",
    "productofInterestSimufact",
    "productofInterestVires",
    "consentProductUpdates",
    "Consent_Remove_from_DB_Request__c",
    "consentStep1",
    "consentStep2",
    "consentStep3",
    "consentWebinarsEvents",
    "Consent_History__c",
    "Consent_Last_Updated__c",
    "consentNotes",
    "Consent_to_Processing__c",
    "consenttosharedatawithpartners",
    "Contact_Comments__c",
    "CurrencyIsoCode_contact",
    "Contact_First_Name_Phonetic__c",
    "Contact_Owner__c",
    "Contact_Owner_Function_MKTO__c",
    "Contact_Rating__c",
    "Contact_Status__c",
    "Contact_Status__c_contact",
    "Contact_Status_Comment__c",
    "Contact_Status_Reason__c",
    "Conversion_Date__c",
    "country",
    "countryB",
    "Country_Used_by_Tech_Support__c",
    "CountryCode",
    "county",
    "Cradle_Contact__c",
    "Cradle_Data__c",
    "Cradle_Memo__c",
    "Cradle_AgreementNo__c",
    "Cradle_CustomerNo__c",
    "Cradle_Industry__c",
    "CRD_Acc_ID__c",
    "CRD_Cont_ID__c",
    "createdAt",
    "Created_by_VG__c",
    "Customer_Number__c",
    "IsCustomerPortal",
    "Technical_Support_Account_Manager_TSAM__c",
    "Data_Source_Id__c",
    "Jigsaw",
    "Jigsaw_account",
    "dateOfBirth",
    "daysdownloadedfile",
    "Deal_Registered_Date_now__c",
    "TARPS__Decision_Date__c",
    "TARPS__Decision_Date__c_account",
    "deliveriesAfterBounces",
    "demographicScore",
    "department",
    "Department__c",
    "Discount_Perc__c",
    "Division_All__c",
    "doNotCall",
    "mktoDoNotCallCause",
    "doNotCallReason",
    "downloadfreetrialfileid",
    "ecosystemCategories",
    "email",
    "emailBounceCategory",
    "emailBounceDetails",
    "EmailBouncedDate",
    "EmailBouncedReason",
    "emailBounces",
    "emailDeliveredAfterBounce",
    "emailInvalid",
    "Email_Invalid__c",
    "emailInvalidCause",
    "Email_of_Field_Sales__c",
    "emailSuspended",
    "emailSuspendedAt",
    "emailSuspendedCause",
    "EMEA_data_protection_policy__c",
    "EMEA_Territory__c",
    "eMEATerritoryB",
    "Entitlement_Status__c",
    "eventAttendance",
    "eventDateCode",
    "eventDateCodeID",
    "eventDateCodeSession",
    "eventDietryRequirements",
    "atEventEventName",
    "Events_Opt_Out__c",
    "Exclude_Overlays_MKTO__c",
    "Existing_Customer__c",
    "Expected_Close_Date__c",
    "Compliance_Status__c",
    "Extension__c",
    "externalCompanyId",
    "externalSalesPersonId",
    "fax",
    "HasOptedOutOfFax",
    "FEM_Usage__c",
    "fftfiledownload",
    "firmographicScore",
    "First_Contact__c",
    "First_MQL_SAL_MKTO__c",
    "First_MQL_SQL_MKTO__c",
    "First_MQL_Date_MKTO__c",
    "firstName",
    "First_name_Phonetic__c",
    "First_Opportunity_Won_Date_MKTO__c",
    "First_Won_Date__c",
    "TARPS__ForceRescreen__c",
    "TARPS__ForceRescreen__c_account",
    "formLanguage",
    "mktoName",
    "Full_Name__c",
    "GeocodeAccuracy",
    "Geography__c",
    "BU_Region__c",
    "globalFormWebPage",
    "hexagonAffiliation",
    "Host_ID__c",
    "ID_18_Digits__c",
    "implicitOptinDate",
    "In_Open__c",
    "In_Return_to_Marketing__c",
    "In_Sales_Accepted__c",
    "In_Will_Never_Buy__c",
    "industry",
    "Industry_Description__c",
    "Industry_Description__c_account",
    "Industry_Segment__c",
    "Industry_Segment__c_lead",
    "inferredCity",
    "inferredCompany",
    "inferredCountry",
    "inferredMetropolitanArea",
    "inferredPhoneAreaCode",
    "inferredPostalCode",
    "inferredStateRegion",
    "Interested_In__c",
    "Interesting_Moment__c",
    "mktoIsCustomer",
    "IsEmailBounced",
    "Is_Open_MQL_MKTO__c",
    "Is_Overlay_the_Logged_in_User__c",
    "mktoIsPartner",
    "isAccount__c",
    "IsAccountConverted__c",
    "isContact__c",
    "isLead__c",
    "JigsawCompanyId_account",
    "JigsawContactId_lead",
    "Job_Function__c",
    "title",
    "Portal_User_Language__c",
    "lastEngagement",
    "lastEngagementDate",
    "lastForm",
    "lastFormHistory",
    "lastName",
    "Last_name_Phonetic__c",
    "Last_Program_Success__c",
    "LastReferencedDate",
    "LastReferencedDate_account",
    "Last_Reporting_Date__c",
    "Last_Status_Change_Date__c",
    "Last_Success_Before_MQL_MKTO__c",
    "LastViewedDate",
    "LastViewedDate_account",
    "Latest_Actioned_Date_MKTO__c",
    "Latest_MQL_SAL_MKTO__c",
    "Latest_MQL_SQL_MKTO__c",
    "Latest_MQL_Date_MKTO__c",
    "Latest_Opportunity_Won_Date_MKTO__c",
    "latestOptinDate",
    "Latest_Return_to_Marketing_Date_MKTO__c",
    "Latitude",
    "Lead_Comments__c",
    "Zone_Region__c",
    "CurrencyIsoCode",
    "leadOwnerB",
    "leadOwnerAssigned",
    "leadOwnerAssignedDate",
    "Lead_Owner_Function__c",
    "Lead_Score_Most_Recent__c",
    "Lead_Status_Reason_Comment__c",
    "Lead_Status_Reason__c",
    "Legacy_System_and_Record_ID__c",
    "Legacy_System_Name__c",
    "Legacy_System_Name__c_contact",
    "Legacy_System_Record_ID__c",
    "Legacy_System_Record_ID__c_contact",
    "Legacy_System_Transfer_Date__c",
    "Legacy_System_Transfer_Date__c_account",
    "legalBasisforCommunication",
    "legalBasisforCommunicationLastUpdated",
    "Legal_Entity_Name__c",
    "Level_of_Interest__c",
    "License_Compliance_Status__c",
    "Lifecycle_Status__c",
    "TARPS__EOD_Link__c",
    "TARPS__EOD_Link__c_account",
    "Linked_Account__c",
    "Location_Type__c",
    "Longitude",
    "magnidIDPassword",
    "MailingAddress",
    "MailingCountryCode",
    "MailingGeocodeAccuracy",
    "MailingLatitude",
    "MailingLongitude",
    "MailingStateCode",
    "mainPhone",
    "marketingSuspended",
    "marketingSuspendedCause",
    "Marketing_Suspended_Date__c",
    "Marketing_Suspended_Reason__c",
    "marketoEventID",
    "facebookDisplayName",
    "facebookId",
    "facebookPhotoURL",
    "facebookProfileURL",
    "facebookReach",
    "facebookReferredEnrollments",
    "facebookReferredVisits",
    "gender",
    "lastReferredEnrollment",
    "lastReferredVisit",
    "linkedInDisplayName",
    "linkedInId",
    "linkedInPhotoURL",
    "linkedInProfileURL",
    "linkedInReach",
    "linkedInReferredEnrollments",
    "linkedInReferredVisits",
    "syndicationId",
    "totalReferredEnrollments",
    "totalReferredVisits",
    "twitterDisplayName",
    "twitterId",
    "twitterPhotoURL",
    "twitterProfileURL",
    "twitterReach",
    "twitterReferredEnrollments",
    "twitterReferredVisits",
    "Marketo_State__c",
    "Max__c",
    "middleName",
    "mobilePhone",
    "MQL_Sync__c",
    "MQL_Sync__c_account",
    "mSCContact",
    "MSC_Partner_Comm_Opt_Out__c",
    "MSC_Product__c",
    "Name_of_Field_Sales__c",
    "neverBounceValidationResult",
    "News_Newsletter_Opt_Out__c",
    "No_Longer_with_Account__c",
    "Tech_Support_Survey__c",
    "numberOfEmployees",
    "Number_of_Employees__c",
    "offeringCategory",
    "offeringsEcosystem",
    "On_Demand_Webinar__c",
    "oneWebSFDCLeadId",
    "MSC_Net__c",
    "orgType",
    "originalAssignedOverlay",
    "originalLeadOwner",
    "Original_Lead_Source__c",
    "originalPersonSource",
    "Original_Product_of_Interest__c",
    "OtherAddress",
    "OtherCountryCode",
    "OtherGeocodeAccuracy",
    "OtherLatitude",
    "OtherLongitude",
    "Other_Products__c",
    "OtherStateCode",
    "Partner_Account__c",
    "IsPartner",
    "Partner_Community_Check__c",
    "partnerSubType",
    "partnerType",
    "Lead_Interest__c",
    "mktoPersonNotes",
    "rating",
    "Lead_Rating__c",
    "leadScore",
    "leadSource",
    "leadStatus",
    "personTimeZone",
    "Phone_Extension__c",
    "phone",
    "PhotoUrl",
    "PhotoUrl_account",
    "physicalEventLevelofinterest",
    "Portfolio_Presentation__c",
    "postCodeB",
    "postalCode",
    "preferredLanguage",
    "Primary_Campaign__c",
    "Primary_Campaign_Function__c",
    "Primary_Customer_Contact__c",
    "priority",
    "processingPerson",
    "product",
    "productEnquiryType",
    "Product_Interest__c",
    "MSC_Products_Solutions_to_be_offered__c",
    "productofInterestB",
    "productofInterestScore",
    "project_timeframe",
    "Publication_flag__c",
    "RAmericas__c",
    "RecordTypeId",
    "RecordTypeId_account",
    "Region__c",
    "Region__c_account",
    "relativeScore",
    "relativeUrgency",
    "Remarks__c",
    "REMEA__c",
    "rescale",
    "resourceAssetID",
    "resourceTitle",
    "resourceType",
    "resourceURL",
    "Responsible_For__c",
    "Retirement__c",
    "Return_to_Marketing_Date_MKTO__c",
    "RingLead_DMS_Status__c",
    "leadRole",
    "Romax_Account_ID__c",
    "Romax_Account_Type__c",
    "Romax_Application__c",
    "Romax_ID__c",
    "Romax_MSC_Match__c",
    "Romax_MSC_Match__c_contact",
    "TARPS__RPL_Update_Inactive__c",
    "TARPS__RPL_Update_Inactive__c_account",
    "runSync",
    "SAL_SQL_MKTO__c",
    "SAL_Date_MKTO__c",
    "Sales_Accepted_Date__c",
    "Sales_Accepted_Days__c",
    "Lead_Owner__c",
    "salutation",
    "Score_at_MQL_MKTO__c",
    "sellingBrand",
    "sendABMAlert",
    "sendHelpdeskAlert",
    "sendMarketingAlert",
    "sendOverlayAlert",
    "sendSalesAlert",
    "sendSalesAlertDateTime",
    "sendSFDCTask",
    "sendSMSReminder",
    "sendSupportAlert",
    "sfdcAccountId",
    "sfdcContactId",
    "sfdcId",
    "sfdcLeadId",
    "sfdcLeadOwnerId",
    "sfdcType",
    "ShippingAddress",
    "ShippingCountryCode",
    "ShippingGeocodeAccuracy",
    "ShippingLatitude",
    "ShippingLongitude",
    "ShippingStateCode",
    "sicCode",
    "SicDesc",
    "consentPreferredCommunication",
    "simufactFreeTrial2",
    "simufactFreeTrial3",
    "simufactFreeTrial3Other",
    "simufactFreeTrial4",
    "simufactFreeTrial4Other",
    "SIRET_Number__c",
    "site",
    "sitecoreItemID",
    "ddc_prospector__Sourced_from_Data_com__c",
    "ddc_prospector__Sourced_from_Data_com__c_account",
    "ddc_prospector__Sourced_from_Data_com__c_contact",
    "SQL_Closed_Lost_MKTO__c",
    "SQL_First_Opportunity_Won_MKTO__c",
    "SQL_Latest_Opportunity_Won_MKTO__c",
    "SQL_Date_MKTO__c",
    "SQL_Date_2_MKTO__c",
    "SRAmericas__c",
    "SRAPAC__c",
    "SREMEA__c",
    "state",
    "stateCanada",
    "StateCode",
    "TARPS__Status__c",
    "TARPS__Status__c_account",
    "Status_Change__c",
    "Sub_Region__c",
    "Sub_Region__c_account",
    "Support_No__c",
    "supportType",
    "Tech_Support_Maintenance_Rev_Tiers__c",
    "tempPersonScore",
    "Time_in_Act_Now__c",
    "Time_in_Current_Status__c",
    "Time_to_Conversion_New__c",
    "Time_to_Conversion__c",
    "Time_to_Sales_Accepted_New__c",
    "Time_to_Sales_Accepted__c",
    "Time_Zone__c",
    "trainingDates",
    "interestofTraining",
    "twilioMessage",
    "Ultimate_Parent__c",
    "university",
    "unsubscribed",
    "unsubscribedReason",
    "updatedAt",
    "urgency",
    "Usage_Reporting_Request_Notes__c",
    "Usage_Reporting_Request_Owner__c",
    "Usage_Reporting_Request_Status__c",
    "Usage_Reporting_Requirement__c",
    "UTM_Campaign__c",
    "UTM_Content__c",
    "uTMContentB",
    "uTMHistory",
    "UTM_Medium__c",
    "UTM_Source__c",
    "UTM_Terms__c",
    "uTWCampaign",
    "VG_RecordId__c",
    "visaArrivalCountry",
    "visaArrivalDate",
    "visaCityApplication",
    "visaDepartureDate",
    "visaIsrequired",
    "visaPassportIssueDate",
    "visaPassportNumber",
    "visaPassportValidityDate",
    "website",
    "Will_Never_Buy_Date_MKTO__c"
]


def create_job(block):
    new_export_job_details = mc.execute(method='create_leads_export_job', fields=output_fields, filters={'createdAt': {'endAt': block[1], 'startAt': block[0]}})
    print(new_export_job_details)
    #data = json.loads(new_export_job_details)
    export_id_array.append(new_export_job_details[0]['exportId'])

def enqueue_job(export_id):
    mc.execute(method='enqueue_leads_export_job', job_id=export_id)

def get_job(export_id):
    export_job_status = mc.execute(method='get_leads_export_job_status', job_id=export_id)
#    data = json.loads(export_job_status)
    status = export_job_status[0]['status']
    print(status)

    if status == "Completed":
        with mc.execute(method='get_leads_export_job_file', job_id=export_id, stream=True) as r:
            with open('data.csv', 'a+b') as f:
                chunk_num = 1
                for chunk in r.iter_content(chunk_size=1024):
                    print('writing chunk ' + str(chunk_num))
                    chunk_num += 1
                    if chunk:
                        f.write(chunk)
    else:
        time.sleep(10)
        get_job(export_id)


for block in block_list:
    create_job(block)

for export_id in export_id_array:
    enqueue_job(export_id)

for export_id in export_id_array:
    get_job(export_id)